mkdir app
mkdir app/sass
mkdir app/coffee
mkdir app/jade
mkdir app/stylus
mkdir app/less
mkdir app/jade/mixins
mkdir app/jade/includes
mkdir app/jade/layouts
mkdir app/src
mkdir app/src/images
mkdir app/src/js
mkdir app/src/css
mkdir public
mkdir public/css
mkdir public/js
mkdir public/assets
mkdir public/fonts
mkdir public/assets/images
mkdir public/assets/videos
mkdir public/assets/audios
bower update
npm install
# gulp
